### ISSUE TITLE
when iframes?

### ISSUE THREAD

**Issue by psy0rz** [wide-video/qov#1]
Very interesting project. I need something like this for mine.

Does it determine if an Iframe is more efficient, or is every frame an iframe exect the initial one?

**Comment by wide-video** [comment]
In terms of I frame vs P frame, the current version of QOV only follows instruction passed as an argument https://github.com/wide-video/qov/blob/master/src/QOV.ts#L58 (see `previous` argument). Simply doing one extra frame encoding, so size of both P and I frames can be compared, would reduce encoding performance by half. Keep "seeking" in mind, there will be a bit more work with headers to be able to guide you to the nearest keyframe etc.

**Comment by psy0rz** [comment]
i was on my phone before, but i understand how it works now.

my usecase is a littlebit different but i got some inspiration from your encoder nonetheless. :)
